# buildspec.yml
version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-2"
    AWS_ACCOUNT_ID: "194453983284"
    IMAGE_REPO_NAME: "myreca"
phases:
  # In the buildspec.yml or your build script
  pre_build:
    commands:
      - pwd
      - ls
      - sed -i 's/TAG="FE"/TAG="FE${CODEBUILD_BUILD_NUMBER}"/g' /scripts/deploy.sh
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:FE$CODEBUILD_BUILD_NUMBER .
      - docker tag $IMAGE_REPO_NAME:FE$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:FE$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:FE$CODEBUILD_BUILD_NUMBER
