apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello-role
rules:
  - apiGroups: [""]
    resources: ["pods"] # Object 지정
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # Action 제어
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-rb
subjects:
  - kind: ServiceAccount
    name: hello-user
roleRef:
  kind: Role
  name: hello-role
  apiGroup: rbac.authorization.k8s.io
